from sounds.perExperiment.sound_elements.sound_class import Sound,Sound_pool,ramp_sound,normalize_sound
from sounds.perExperiment.sound_elements.tones_elements import Bip,Bip_randPitch,gaussian_N,Silence
from sounds.perExperiment.sound_elements.speech_elements import FrenchSyllable
