from sounds.perExperiment.sound_elements.sound_class import Sound,Sound_pool
from sounds.perExperiment.sound_elements.sound_class import ramp_sound,normalize_sound,pitch_shift
from sounds.perExperiment.sound_elements.tones_elements import Bip,Bip_randPitch,Silence
from sounds.perExperiment.sound_elements.speech_elements import FrenchSyllable
