from sounds.perExperiment.sequences.seq_class import Sequence
from sounds.perExperiment.sequences.patterns import Random_tone,Local_Standard,Local_Deviant
from sounds.perExperiment.sequences.patterns import FullCommunityGraph,SparseCommunityGraph